# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Fetcher', '0002_auto_20170407_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
